name: dc-lb
services:
  frontend:
    container_name: dc-lb-frontend
    build:
      context: ./src/frontend
      dockerfile: ./df-prod.Dockerfile
      args:
        - MOUNT_PATH=/dc/lineage-builder/
    ports:
      - 90:8080
    depends_on:
      - api
      - db
    restart: always
    networks:
      - dc
      - internal

  api:
    container_name: dc-lb-api
    build:
      context: ./src/backend
      dockerfile: ./df-prod.Dockerfile
    depends_on:
      - db
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
    networks:
      - internal

  db:
    container_name: dc-lb-db
    image: mariadb:10
    restart: always
    tty: true
    volumes:
      - ./src/db/prod:/docker-entrypoint-initdb.d
      - builder_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - internal

volumes:
  builder_db:

networks:
  internal:
  dc:
    external: true